import type { Metadata } from 'next';

import './globals.css';
import { openSans } from '@/utils/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="">
            <body className={`${openSans.className}  antialiased`}>
                <main className="min-h-screen light">{children}</main>
            </body>
        </html>
    );
}
